apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-demo-app  # Ensure it matches the base deployment
spec:
  replicas: 1  # Fewer replicas for dev environment
  template:
    spec:
      containers:
      - name: gitops-demo-container  # Matches the base container name
        image: docker.io/yahyaalshamrani/gitops-demo-app:v0.1.2
        env:
          - name: SECRET
            valuefrom: 
              secretKeyRef:
                name: message
                key: SECRET
