apiVersion: v1
kind: Secret
metadata:
  name: pullsecret  # Pull secret name
  namespace: default  # Namespace
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: <base64-encoded-auth-json>  # Replace this with the actual Base64-encoded credentials

